### ISSUE TITLE
Memory Error when running for 24-hr

### ISSUE THREAD

**Issue by stevenagy** [sslab-gatech/qsym#21]
Hello,

I've been running QSYM with 1xAFL (slave), and after running for about 20-24hrs, QSYM seems to crash irregularly. I didn't manage to get save the full error report, but I recall it containing something along the lines of "Memory Error". 

My environment of choice is a Ubuntu-16.04 x64 VM with 4gigs of RAM and 3 cores. 

Any ideas? Could this mean QSYM is maxing-out its python data structures?

Thanks,
-Stefan

**Comment by stevenagy** [comment]
I re-ran for 20h and ran into the following different error:

`OSError: [Errno 2] No such file or directory: 'readelf_qsym_afl-qemu/afl-slave/queue/id:000249,src:000002+000098,op:splice,rep:4'`

Any suggestions would be greatly appreciated.

**Comment by jakkdu** [comment]
Hi, Stefan. Sorry, I have no idea about the first and second bug.
I couldn't see the same error before.
Our machine has 256 GB RAM as noted in the paper.
So that might be the reason that I counldn't see the memory error.
The second bug seems it cannot find the file.
But the file should be there since we get the file from notification.

If you find any more clue, then let me know.
Sorry for your inconvenience.

**Comment by insuyun** [comment]
Close this issue and will re-open if this happens again.
