### ISSUE TITLE
Question about makeAddrConcrete

### ISSUE THREAD

**Issue by 5hadowblad3** [sslab-gatech/qsym#42]
Hi,

QSYM is a great tool. 

Recently when I look at the code, I have one question.

Can I ask why qsym will produce new input when calling makeAddrConcrete? What is this function actually does? I thought it was for getting the value from a certain address?

Regards,

**Comment by jakkdu** [comment]
Hi,.
One of the problem of symbolic execution is handling symbolic pointer. There is some work that can handle symbolic pointer (e.g., KLEE), but it is extremely slow. Thus, many symbolic execution engines concretize the pointer.

In QSYM, we also concretize the pointer. But for finding some bugs related to boundary,  it tries to generate minimum and maximum values for the boundary cases before concretization (see [this](https://github.com/sslab-gatech/qsym/blob/3703ef50c27a5c7447bbf9de7709731cd2baa6e8/qsym/pintool/solver.cpp#L195)).

This is similar to [SimConcretizationStrategyMax](https://github.com/angr/angr/blob/e27313be7b650472e768489fb500b56078cef45b/angr/concretization_strategies/max.py) in angr, but max as well as min.

Let's assume that the concrete input for index is 0 for the following code.
```
int arr = {0xdeadbeef, 0xbadf00d};
int index = input();
if (index < 2)
   return;

if (arr[index] == 0xdeadbeef) { -> (1)
  ... (2)
}
```

Since `arr[index]` is symbolic pointer, QSYM tries to concretize index. Before concretization, QSYM will generate test case for negative index (min) and index = 1 (max), and after branch (1), index will be fixed as 0, which is the initial input.

This heuristics loses completeness of symbolic execution, but can gain performance. If you need more careful analysis about symbolic pointers, you can use KLEE. (or angr I guess).

Thank you.

Best,
Insu Yun.

**Comment by 5hadowblad3** [comment]
Thank you so much for answering. 

I think I understand more about the whole framework!

**Comment by jakkdu** [comment]
Sounds good :)
