### ISSUE TITLE
Does qsym not feed testcases from qsym/queue back into AFL ?

### ISSUE THREAD

**Issue by inferno-chromium** [sslab-gatech/qsym#62]
Reading the code, looks like the new testcases you find and store in qsym/queue, you don't feed them back into AFL. Is that right ?

**Comment by jakkdu** [comment]
No. If I put it to qsym/queue, AFL will collect these inputs periodically. FYI, https://github.com/google/AFL/blob/master/afl-fuzz.c#L6666

**Comment by inferno-chromium** [comment]
Another question, do you really need a afl-master and afl-slave ? It can be just run with a afl-master right ?

**Comment by jakkdu** [comment]
If you want to have only one AFL instance, I suggest you to use afl-slave instead of afl-master. Because of AFL's exhaustive deterministic phase, AFL sometimes stuck at deterministic phase for a large file. Because QSYM decides its next input based on AFL, if AFL stuck, QSYM also stuck. Compared to deterministic phase, a random phase (havoc) take shorter time, this does not happen. But still, I believe that the deterministic phase has its own value, so I used two instances, master and slave.

**Comment by inferno-chromium** [comment]
Ok thanks!

**Comment by zhanggenex** [comment]
@jakkdu 
Hi, is any way to **keep both** the deterministic and undeterministic stages in AFL when running QSYM? (The master has no undeterministic and the slave has no deterministic).

I tried to run QSYM with **-a ""**, AFL without **-M** and **-S**, but AFL did not import any seeds from the qsym directory.
Any idea to this problem?
Thanks
