### ISSUE TITLE
Question about trace_map in QSYM

### ISSUE THREAD

**Issue by White-Mouse** [sslab-gatech/qsym#83]
QSYM use trace_map to judge whether the branch is interesting in afl_trace_map.cpp. So I have a question about that whether the trace_map is the same as  the trace_bit in AFL?  In other words, whether the edge id in the QSYM is the same as the instrumented edge id in AFL?

**Comment by insuyun** [comment]
Hi. @White-Mouse.

QSYM is maintaining its own coverage bitmap.
This is conceptually equal to AFL's one, but not same.
(i.e., the edge id in the QSYM is not equal to the one in AFL).

This is because of inconsistencies in binaries of QSYM and AFL.
As you can see from our example, QSYM uses non-instrumented binary unlike AFL.
Thus, it is difficult to match branch between these two systems.

Moreover, QSYM's branch is more sensitive than AFL's one.
In particular, QSYM's branch considers call stacks unlike AFL

https://github.com/sslab-gatech/qsym/blob/4fa4363cd09d40a422efa24d359b87f849202d4a/qsym/pintool/afl_trace_map.cpp#L70-L105

This allows QSYM to solve more branches for discovering interesting paths.

**Comment by White-Mouse** [comment]
Thank you for your reply!
